openapi: 3.0.0
info:
  title: Stock Transaction API
  description: This API provides access to stock trading transaction data.
  version: 1.0.0
servers:
  - url: https://api.34-110-134-67.nip.io
security:
  - ApiKeyAuth: []
paths:
  /transactions:
    get:
      description: Get a list of all transactions.
      operationId: getTransactions
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Transaction'
                type: array
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Forbidden
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Not Found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Internal Server Error
      tags:
        - transactions
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: apikey
      in: query
  schemas:
    Error:
      description: Error object
      properties:
        message:
          description: The error message
          type: string
      type: object
    Transaction:
      description: A transaction represents a trade of a stock.
      properties:
        CFICode:
          description: The CFICode of the transaction.
          type: string
        LastPx:
          description: The last price of the transaction.
          type: string
        MaturityDate:
          description: The maturity date of the transaction.
          type: string
        OrderID:
          description: The unique order identifier of the transaction.
          type: string
        Quantity:
          description: The quantity of the transaction.
          type: string
        SenderCompID:
          description: The SenderCompID of the transaction.
          type: string
        SendingTime:
          description: The SendingTime of the transaction.
          type: string
        StrikePrice:
          description: The StrikePrice of the transaction.
          type: string
        Symbol:
          description: The symbol of the stock.
          type: string
        TargetCompID:
          description: The unique identifier of the comp transaction.
          type: string
        TradeDate:
          description: The trade date of the transaction.
          type: string
        TradeReportId:
          description: The unique identifier of the trade report.
          type: string
        TransactTime:
          description: The transaction time.
          type: string
      type: object
